Debian (#1)
Debian and OSX

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,8 +4,6 @@ on:
   push:
     tags:
       - 'v*'
-    # branches:
-    #   - develop
 
 defaults:
   run:
@@ -43,44 +41,72 @@ jobs:
               --generate-notes $OPTIONS
 
   build:
-    name: Build on ${{ matrix.name }}
+    name: Build on ${{ matrix.container && matrix.container.image || matrix.name }} (${{ matrix.arch }})
     runs-on: ${{ matrix.os }}
     needs: [release]
+    container: ${{ matrix.container && matrix.container || null }}
     strategy:
-      #fail-fast: false
       matrix:
         include:
+          - os: [ubuntu-24.04-arm]
+            target: Linux
+            name: ubuntu24
+            flavour: debian
+            arch: arm64
+
           - os: [ubuntu-24.04]
             target: Linux
             name: ubuntu24
             flavour: debian
+            arch: amd64
 
           - os: [ubuntu-22.04]
             target: Linux
             name: ubuntu22
             flavour: debian
+            arch: amd64
 
-          # - os: [ubuntu-22.04]
-          #   target: Linux
-          #   name: rocky9
-          #   flavour: redhat
-          #   container:
-          #     image: rockylinux/rockylinux:9
+          - os: [ubuntu-22.04]
+            target: Linux
+            name: rocky9
+            flavour: redhat
+            arch: amd64
+            container:
+              image: rockylinux:9
+
+          - os: [ubuntu-22.04]
+            target: Linux
+            name: debian11
+            flavour: debian
+            arch: amd64
+            container:
+              image: debian:11
+
+          - os: [ubuntu-22.04]
+            target: Linux
+            name: debian12
+            flavour: debian
+            arch: amd64
+            container:
+              image: debian:12
 
           # X86
           # - os: macos-13
           #   target: Macos
           #   flavour: mac
+          #   name: Macos13
 
           - os: macos-14
             target: Macos
             flavour: mac
+            arch: arm64
             name: Macos14
 
           - os: [self-hosted, Windows]
             target: Windows
             flavour: windows
             name: Windows
+            arch: amd64
 
     steps:
       - name: Checkout Repository
@@ -98,9 +124,15 @@ jobs:
           echo "VERSION=$VERSION" >> $env:GITHUB_ENV
         shell: powershell
 
+      - name: RedHat pre-reqs
+        if: ${{ matrix.flavour == 'redhat' }}
+        run: |
+          dnf -y install epel-release
+          dnf -y install lsb_release
+
       - name: Setup Python v3.11
         uses: actions/setup-python@v5
-        if: ${{ matrix.target == 'Linux' }}
+        if: ${{ matrix.container == null && matrix.flavour != 'windows' }}
         with:
           python-version: 3.11
           cache: "pip"
@@ -128,26 +160,63 @@ jobs:
         run: |
           export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
           echo "PATH=$PATH" >> $GITHUB_ENV
+
           brew install python@3.11 gcc make libev
 
       - name: Compile and build (Ubuntu/Debian)
         if: ${{ matrix.target != 'Windows' }}
         run: |
-          if [ "${{ matrix.flavour }}" == "debian" ]; then
-            sudo apt-get update
-            sudo apt-get install -y build-essential libev-dev make libc6-dev ruby-rubygems
+          set -ex
+          if ! command -v sudo &> /dev/null; then
+            SUDO=""
+          else
+            SUDO="sudo"
           fi
-          python -m venv venv
+
+          if [ "${{ matrix.flavour }}" == "debian" ]; then
+            $SUDO apt-get update
+            $SUDO apt-get install -y build-essential libev-dev make libc6-dev rubygems
+            [[ "${{ matrix.name }}" == "debian12" ]] && $SUDO apt-get install -y --ignore-missing python3.11 python3.11-venv python3.11-dev
+            [[ "${{ matrix.name }}" == "debian11" ]] && $SUDO apt-get install -y --ignore-missing python3 python3-venv python3-dev python3-pip
+          elif [ "${{ matrix.flavour }}" == "redhat" ]; then
+            if ! command -v dnf &> /dev/null; then
+              echo "Installing dnf..."
+              microdnf install -y dnf
+            fi
+            dnf install -y gcc make libev-devel python3.11-pip python3.11-setuptools python3.11-devel glibc-devel rubygems rpm-build
+          fi
+          
+          if command -v python3.11 &> /dev/null; then
+            PYTHON=$(command -v python3.11)
+          elif command -v python3 &> /dev/null; then
+            PYTHON=$(command -v python3)
+          elif command -v python &> /dev/null; then
+            PYTHON=$(command -v python)
+          else
+            echo "Python not found"
+            exit 1
+          fi
+
+          $PYTHON -m venv venv
           source venv/bin/activate
-          python3 -m ensurepip
-          pip3 install cython setuptools
+          export PYTHON=$(pwd)/venv/bin/python
+          $PYTHON -m ensurepip
+
+          [ "${{ matrix.flavour }}" == "readht" ] && $PYTHON -m pip install setuptools
+          $PYTHON -m pip install cython
+
           ./configure
-          make -j4
+
+          if command -v gmake &> /dev/null; then
+            MAKE=$(command -v gmake)
+          else
+            MAKE=$(command -v make)
+          fi
+          $MAKE -j4 PYTHON_CMD=${PYTHON}
 
       - name: Compile and build (Windows)
         if: ${{ matrix.target == 'Windows' }}
         run: |
-          hostname
           make -f Makefile.win build
         shell: cmd
 
@@ -164,7 +233,11 @@ jobs:
       - name: Linux/OSX create package
         if: ${{ matrix.target != 'Windows' }}
         run: |
-          gem install --no-document --user fpm
+          if [ $(id -u) -gt 0 ]; then
+            gem install --no-document --user fpm
+          else
+            gem install --no-document fpm
+          fi
           ./package.sh ${VERSION}
 
       - name: Upload Artifacts
