Debian

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,83 +4,83 @@ on:
   push:
     tags:
       - 'v*'
-    # branches:
-    #   - develop
+    branches:
+      - debian
 
 defaults:
   run:
     shell: bash
 
 jobs:
-  release:
-    name: Create Release
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # release:
+  #   name: Create Release
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Fail if tag is not prefixed by v
-        run: |
-          if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9].* ]]; then
-              echo "Valid version format"
-          else
-              echo "Invalid version format"
-              exit 1
-          fi
+  #     - name: Fail if tag is not prefixed by v
+  #       run: |
+  #         if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9].* ]]; then
+  #             echo "Valid version format"
+  #         else
+  #             echo "Invalid version format"
+  #             exit 1
+  #         fi
 
-      - name: Create release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          tag: ${{ github.ref_name }}
-        run: |
-          OPTIONS=""
-          if [[ $GITHUB_REF_NAME == *"internal"* ]]; then
-            OPTIONS="--prerelease"
-          fi
-          gh release create "$GITHUB_REF_NAME" \
-              --repo="$GITHUB_REPOSITORY" \
-              --title="Release for ${GITHUB_REF_NAME}" \
-              --generate-notes $OPTIONS
+  #     - name: Create release
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         tag: ${{ github.ref_name }}
+  #       run: |
+  #         OPTIONS=""
+  #         if [[ $GITHUB_REF_NAME == *"internal"* ]]; then
+  #           OPTIONS="--prerelease"
+  #         fi
+  #         gh release create "$GITHUB_REF_NAME" \
+  #             --repo="$GITHUB_REPOSITORY" \
+  #             --title="Release for ${GITHUB_REF_NAME}" \
+  #             --generate-notes $OPTIONS
 
   build:
     name: Build on ${{ matrix.name }}
     runs-on: ${{ matrix.os }}
-    needs: [release]
+    #needs: [release]
     strategy:
       #fail-fast: false
       matrix:
         include:
-          - os: [ubuntu-24.04]
-            target: Linux
-            name: ubuntu24
-            flavour: debian
-
-          - os: [ubuntu-22.04]
-            target: Linux
-            name: ubuntu22
-            flavour: debian
+          # - os: [ubuntu-24.04]
+          #   target: Linux
+          #   name: ubuntu24
+          #   flavour: debian
 
           # - os: [ubuntu-22.04]
           #   target: Linux
-          #   name: rocky9
-          #   flavour: redhat
-          #   container:
-          #     image: rockylinux/rockylinux:9
+          #   name: ubuntu22
+          #   flavour: debian
+
+          - os: [ubuntu-22.04]
+            target: Linux
+            name: rocky9
+            flavour: redhat
+            container:
+              image: rockylinux/rockylinux:9
 
           # X86
           # - os: macos-13
           #   target: Macos
           #   flavour: mac
 
-          - os: macos-14
-            target: Macos
-            flavour: mac
-            name: Macos14
+          # - os: macos-14
+          #   target: Macos
+          #   flavour: mac
+          #   name: Macos14
 
-          - os: [self-hosted, Windows]
-            target: Windows
-            flavour: windows
-            name: Windows
+          # - os: [self-hosted, Windows]
+          #   target: Windows
+          #   flavour: windows
+          #   name: Windows
 
     steps:
       - name: Checkout Repository
